name: Java CI with Maven

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload Agent Jar
      uses: actions/upload-artifact@v4
      with:
        name: unsafe-class-agent
        path: target/unsafe-class-agent-*-jar-with-dependencies.jar

    - name: Create Pre-release
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        name: Latest Pre-release
        prerelease: true
        generate_release_notes: true
        files: target/unsafe-class-agent-*-jar-with-dependencies.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
